language: node_js
node_js:
  - '0.12'
  - '4.4.0'
  - '5.5.0'
sudo: false
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'gem install sass'
  - 'gem install compass'
  - 'grunt'
